apiVersion: v1
kind: Service
metadata:
  name: liatrio-message-api-service
spec:
  type: LoadBalancer
  selector:
    app: liatrio-message-api
  ports: 
    - protocol: TCP
      port: 80
      targetPort: 4242